
services:
  nextjs-app:
    image: node:20-alpine
    container_name: ai-trade
    working_dir: /app
    command: sh -c "npm install && npm run build && npm start"
    volumes:
      - /opt/apps/nextjs-app:/app
    restart: unless-stopped
    expose:
      - "3010"
    networks:
      - docker_default

networks:
  docker_default:
    external: true